# Generated by Django 2.1.2 on 2018-11-28 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slogan', models.CharField(default=None, max_length=30, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=3.0, max_digits=3)),
                ('sport_id', models.ForeignKey(default=None, on_delete='sport_id', to='player.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='TeamColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(default='FFFFFF', max_length=6, null=True)),
                ('secondary', models.CharField(default='FFFFFF', max_length=6, null=True)),
                ('tertiary', models.CharField(default='FFFFFF', max_length=6, null=True)),
                ('team_id', models.ForeignKey(default=None, on_delete='team_id', to='player.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(default=None, null=True)),
                ('player_id', models.ForeignKey(default=None, on_delete='player_id', to='player.Player')),
                ('team_id', models.ForeignKey(default=None, on_delete='team_id', to='player.Team')),
            ],
        ),
    ]
